
CREATE TABLE ideas (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    project_title TEXT NOT NULL,
    project_summary TEXT NOT NULL, 
    date_submitted TIMESTAMP DEFAULT now() NOT NULL,
    github TEXT,
    votes NUMERIC DEFAULT 0
)