CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT,
    nickname TEXT NOT NULL,
    date_created TIMESTAMP NOT NULL DEFAULT now()
);

ALTER TABLE ideas
    ADD COLUMN
        author INTEGER REFERENCES users(id)
        ON DELETE SET NULL;