TRUNCATE comments_votes, ideas_votes, comments, ideas, users, RESTART IDENTITY CASCADE;

INSERT INTO users (first_name, last_name, email, password, nickname, votes, date_created) 
    VALUES('John', 'Doe', 'jdoe@developmenttesting.com', '$2a$12$d515ftTi6hRTdV.0r1xr5.Hbrd8V3W0yIA0guPghw6I6DQRADzCGm', 'code_guru', '77', '2020-12-21T07:00:00.000Z'),
    ('Luke', 'Doe', 'ldoe@developmenttesting.com', '$2a$12$S6MdndQF3HX6H8bLzMbl0ekpTvjiEb4rTal92xFuBcxY4MNfnERxC', 'react_champ', '35', '2020-12-21T07:00:00.000Z'),
    ('Bob', 'Doe', 'bdoe@developmenttesting.com', '$2a$12$X6XpGevXZ6pFgmp4PTq94OyKl17eSGY2gDcheocYcwCFKiLHR8DGa', 'jquery_king', '20', '2020-12-21T07:00:00.000Z'),
    ('Steve', 'Doe', 'sdoe@developmenttesting.com', '$2a$12$NeuK9BNnjouafYcSXfshd.QRSErVD4K.S4N0LPhjQzC1/ymCJf46m', 'css_aficianado', '15', '2020-12-21T07:00:00.000Z');

INSERT INTO ideas (project_title, project_summary, date_submitted, github, votes, status, author)
VALUES
    ('First Project', 'Lorem ipsum dolor sit amet, te autem soluta facilisi vel, feugiat perfecto sapientem sit ei, in sit electram abhorreant. Ne nam aeterno labitur admodum, qui timeam quaerendum ullamcorper ut. Porro debet molestie eu duo, sea no essent feugait. In nec atqui scaevola, ea sed everti sanctus convenire. Ea quod discere pri, hinc incorrupte ne his.', '2019-12-18T07:00:00.000Z', 'https://www.google.com/', 15, 'Idea', 1),
    ('Second Project', 'Lorem ipsum dolor sit amet, te autem soluta facilisi vel, feugiat perfecto sapientem sit ei, in sit electram abhorreant. Ne nam aeterno labitur admodum, qui timeam quaerendum ullamcorper ut. Porro debet molestie eu duo, sea no essent feugait. In nec atqui scaevola, ea sed everti sanctus convenire. Ea quod discere pri, hinc incorrupte ne his.', '2019-12-21T07:00:00.000Z', 'https://www.google.com/', 6, 'Idea', 2),
    ('Third Project', 'Lorem ipsum dolor sit amet, te autem soluta facilisi vel, feugiat perfecto sapientem sit ei, in sit electram abhorreant. Ne nam aeterno labitur admodum, qui timeam quaerendum ullamcorper ut. Porro debet molestie eu duo, sea no essent feugait. In nec atqui scaevola, ea sed everti sanctus convenire. Ea quod discere pri, hinc incorrupte ne his.', '2020-01-05T07:00:00.000Z', 'https://www.google.com/', 27, 'Idea', 3),
    ('Fourth Project', 'Lorem ipsum dolor sit amet, te autem soluta facilisi vel, feugiat perfecto sapientem sit ei, in sit electram abhorreant. Ne nam aeterno labitur admodum, qui timeam quaerendum ullamcorper ut. Porro debet molestie eu duo, sea no essent feugait. In nec atqui scaevola, ea sed everti sanctus convenire. Ea quod discere pri, hinc incorrupte ne his.', '2020-02-04T07:00:00.000Z', 'https://www.google.com/', 0, 'Idea', 4);


INSERT INTO comments (comment_text, votes, date_submitted, author, project)
    VALUES
        ('Ne velit facilis deserunt nam, eum lucilius constituto ex. Odio rebum dignissim ad mel, an ius tollit veniam, vix vidit mazim homero ad. Paulo definitiones et mei, nam ne illum scripta. Zril senserit at has, at est clita eirmod moderatius. Et mnesarchum posidonium sea, aliquid debitis oportere qui et. Vix no ullum adipiscing, an qui nulla temporibus.', 15, '2020-01-30T07:00:00.000Z', 1, 1),
        ('Ne velit facilis deserunt nam, eum lucilius constituto ex. Odio rebum dignissim ad mel, an ius tollit veniam, vix vidit mazim homero ad. Paulo definitiones et mei, nam ne illum scripta. Zril senserit at has, at est clita eirmod moderatius. Et mnesarchum posidonium sea, aliquid debitis oportere qui et. Vix no ullum adipiscing, an qui nulla temporibus.', 5, '2020-01-30T07:00:00.000Z', 2, 1),
        ('Ne velit facilis deserunt nam, eum lucilius constituto ex. Odio rebum dignissim ad mel, an ius tollit veniam, vix vidit mazim homero ad. Paulo definitiones et mei, nam ne illum scripta. Zril senserit at has, at est clita eirmod moderatius. Et mnesarchum posidonium sea, aliquid debitis oportere qui et. Vix no ullum adipiscing, an qui nulla temporibus.', 2, '2020-01-30T07:00:00.000Z', 3, 1),
        ('Ne velit facilis deserunt nam, eum lucilius constituto ex. Odio rebum dignissim ad mel, an ius tollit veniam, vix vidit mazim homero ad. Paulo definitiones et mei, nam ne illum scripta. Zril senserit at has, at est clita eirmod moderatius. Et mnesarchum posidonium sea, aliquid debitis oportere qui et. Vix no ullum adipiscing, an qui nulla temporibus.', 33, '2020-01-30T07:00:00.000Z', 1, 2),
        ('Ne velit facilis deserunt nam, eum lucilius constituto ex. Odio rebum dignissim ad mel, an ius tollit veniam, vix vidit mazim homero ad. Paulo definitiones et mei, nam ne illum scripta. Zril senserit at has, at est clita eirmod moderatius. Et mnesarchum posidonium sea, aliquid debitis oportere qui et. Vix no ullum adipiscing, an qui nulla temporibus.', 1, '2020-01-30T07:00:00.000Z', 2, 2),
        ('Ne velit facilis deserunt nam, eum lucilius constituto ex. Odio rebum dignissim ad mel, an ius tollit veniam, vix vidit mazim homero ad. Paulo definitiones et mei, nam ne illum scripta. Zril senserit at has, at est clita eirmod moderatius. Et mnesarchum posidonium sea, aliquid debitis oportere qui et. Vix no ullum adipiscing, an qui nulla temporibus.', 0, '2020-01-30T07:00:00.000Z', 3, 2),
        ('Ne velit facilis deserunt nam, eum lucilius constituto ex. Odio rebum dignissim ad mel, an ius tollit veniam, vix vidit mazim homero ad. Paulo definitiones et mei, nam ne illum scripta. Zril senserit at has, at est clita eirmod moderatius. Et mnesarchum posidonium sea, aliquid debitis oportere qui et. Vix no ullum adipiscing, an qui nulla temporibus.', 19, '2020-01-30T07:00:00.000Z', 1, 3),
        ('Ne velit facilis deserunt nam, eum lucilius constituto ex. Odio rebum dignissim ad mel, an ius tollit veniam, vix vidit mazim homero ad. Paulo definitiones et mei, nam ne illum scripta. Zril senserit at has, at est clita eirmod moderatius. Et mnesarchum posidonium sea, aliquid debitis oportere qui et. Vix no ullum adipiscing, an qui nulla temporibus.', 43, '2020-01-30T07:00:00.000Z', 2, 3),
        ('Ne velit facilis deserunt nam, eum lucilius constituto ex. Odio rebum dignissim ad mel, an ius tollit veniam, vix vidit mazim homero ad. Paulo definitiones et mei, nam ne illum scripta. Zril senserit at has, at est clita eirmod moderatius. Et mnesarchum posidonium sea, aliquid debitis oportere qui et. Vix no ullum adipiscing, an qui nulla temporibus.', 27, '2020-01-30T07:00:00.000Z', 3, 3),
        ('Ne velit facilis deserunt nam, eum lucilius constituto ex. Odio rebum dignissim ad mel, an ius tollit veniam, vix vidit mazim homero ad. Paulo definitiones et mei, nam ne illum scripta. Zril senserit at has, at est clita eirmod moderatius. Et mnesarchum posidonium sea, aliquid debitis oportere qui et. Vix no ullum adipiscing, an qui nulla temporibus.', 8, '2020-01-30T07:00:00.000Z', 1, 4),
        ('Ne velit facilis deserunt nam, eum lucilius constituto ex. Odio rebum dignissim ad mel, an ius tollit veniam, vix vidit mazim homero ad. Paulo definitiones et mei, nam ne illum scripta. Zril senserit at has, at est clita eirmod moderatius. Et mnesarchum posidonium sea, aliquid debitis oportere qui et. Vix no ullum adipiscing, an qui nulla temporibus.', 7, '2020-01-30T07:00:00.000Z', 2, 4),
        ('Ne velit facilis deserunt nam, eum lucilius constituto ex. Odio rebum dignissim ad mel, an ius tollit veniam, vix vidit mazim homero ad. Paulo definitiones et mei, nam ne illum scripta. Zril senserit at has, at est clita eirmod moderatius. Et mnesarchum posidonium sea, aliquid debitis oportere qui et. Vix no ullum adipiscing, an qui nulla temporibus.', 5, '2020-01-30T07:00:00.000Z', 3, 4);






